---
title: "Introduction to R (1st part)"
author: Andreas Kitsche
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

R is a language and environment for statistical computing and graphics. R is available as Free Software.
It compiles and runs on a wide variety of UNIX platforms and similar systems, Windows and MacOS.

##Installation of R
R can be downloaded from http://www.r-project.org/. A manual *R Installation and Administration* is also available on this website. Also the manual *An Introduction to R* can be found there.   
We recommend the use of an editor. The use of an editor interface to R gives additional functionality. There are several editors available for R, e.g.:

* Emacs
* Tinn-R
* WinEdt
* R-Studio

For this introductory course we will use the R-Studio editor which is available under http://rstudio.org/. A very fine documentation on how to use R-Studio is given on http://rstudio.org/docs/.

Recording your work: we prefer to keep a record of the commands you entered, so that you can reproduce the workspace at a later date. 
You can find some introductory material for R on the following link


* John Verzani: simpleR - [Using R for Introductory Statistics](http://cran.r-project.org/doc/contrib/Verzani-SimpleR.pdf) 
* Emmanuel Paradis: [R for Beginners](http://cran.r-project.org/doc/contrib/Paradis-rdebuts_en.pdf)
* Tom Short: [R Reference Card](http://cran.r-project.org/doc/contrib/Short-refcard.pdf)



##Using R as a calculator
At its basic level, R can be viewed as a fancy calculator.

```{chunk1, cache=TRUE}
2 + 2
3^4
7 * 4 + 3
```
R has a workspace known as the global environment that can be used to store the results of calculations and many other types of objects.
We tell R to make the assignment using an arrow that points to the left. We can see the results of this assignment by typing the name of our new object.
```{chunk2, cache=TRUE}
object1 <- 72^9 + 10
object1
```

##Types of data
There are several types of data implemented in R. You can check the type of an object with the `mode()` command:
```{chunk3, cache=TRUE}
mode(object1)
```
The simplest types are logical values which are represented by `TRUE`TRUE and `FALSE`. The next higher ordered type of data are integer values. Integer values can be generated via the `as.integer()` function:

```{chunk4, cache=TRUE}
mode(3.245) #obviously 3.245 is of type "numeric"
as.integer(3.245) #transforms the numeric value of "3.245" into an integer one
```
The next higher ordered type of data are numeric variables, i.e. 3.245. Another type of data are character data that consists of letters and strings:
```{chunk5, cache=TRUE}
"hello, how are you?"
mode("hello, how are you?")
```

\section{Types of objects}
\subsection{Vectors}
A numeric vector is a list of numbers. The `c()` function is used to collect things together into a vector. We can type
```{chunk6, cache=TRUE}
c(4,9,12)
```
Again, we ca assign this to a named object
```{chunk7_1, cache=TRUE}
object2 <- c(4,9,12) # the "#" sign can be used to commend lines
object2
```
The : symbol can be used to create sequences of values. For example,
```{chunk7_2, cache=TRUE}
object3 <- 10:20
object3
```
Extracting elements from a vector is possible by using square brackets:
```{chunk8,cache=TRUE}
object3[5] #extracts the 5th element from object3
```
Negative indices can be used to avoid certain elements.
```{chunik9, cache=TRUE}
object3[-5] #selects all but the 5th element of object3
```
Also arithmetic can be done on R vectors. The computation is performed element-wise. 
```{chunk10, cache=TRUE}
object3 * 3 #multiply all elements of object3 with 3
```
Vector arithmetics also work element-by-element when applied to pairs of vectors. When the vectors are of different length, the shorter one is extended by recycling: values are repeated, starting at the beginning.
```{chunk11, cache=TRUE, warning=FALSE}
object2
object3
object2 + object3
```
Patterned vectors can also be produced using the `seq()` function as well as the `rep()` function.
```{chunk12, cache=TRUE}
seq(5, 15, by=2)
rep(1, 10)
```
The missing value symbol is `NA`. Missing values often arise in real data problems, but they can also arise because of the way calculations are performed.
```{chunk13, cache=TRUE}
object3[20]
```
Note that there is a second kind of "missing" values which are produced by numerical computation, the so called "Not a Number", `NaN`, values.
```{chunk14, cache=TRUE}
0/0
```
R also allows manipulation of logical quantities. The elements of a logical vectors can have the values `TRUE, FALSE` and `NA`. Logical vector are generated by conditions. For example:
```{chunk15, cache=TRUE}
object3
object3 < 15
```
Logical operators are `<,<=,>,>=,==` for exact equality and `!=` for inequality. In addition if `c1` and `c2` are logical expressions, then `c1 & c2` is their intersection (``and''), `c1|c2` is their union (``or'').
```{chunk16, cache=TRUE}
(object3 <= 13) & (object3 <=17)
(object3 <= 13) | (object3 <=17)
```
Scalars and vectors can also be made of strings of characters instead of numbers. All elements of a vector must be of the same type. 
```{chunk17, cache=TRUE}
colors <- c("red", "green", "blue")
colors
```
Factors offer an alternative way of storing character data. For example a factor with six elements and having two levels:
```{chunk18, cache=TRUE}
object4 <- rep(c("control","treatment"),3)
object4
factor(object4)
```
\subsection{Matrices}
A matrix is a rectangular array of numbers, symbols, or expressions. In fact, matrices are multi-dimensional generalizations of vectors. To arrange values into a matrix, we use the `matrix()` function:
```{chunk19, cache=TRUE}
matrix1 <- matrix(1:16, nrow=4, ncol=4)
matrix1
```
Matrices can be indexed by two indices:
```{chunk20, cache=TRUE}
matrix1[1,3]
```
Whole rows ore columns of matrices may be selected by leaving the corresponding index blank:
```{chunk21, cache=TRUE}
matrix1[2,]
matrix1[,1]
```
\subsection{Data Frames}
Data frames are matrix-like structures, with the columns having their own names. Columns can be of different types from each other.  Most data sets are stored in R as data frames. Think of data frames as "data matrices" with one row per observational unit. 
Use the `data.frame` function to construct data frames from vectors:
```{chunk22, cache=TRUE}
colors2 <- c("red","blue","yellow","green")
numbers <- 1:4
type <- c("1st","2nd","3rd",NA)
object5 <- data.frame(colors2, numbers, type)
object5
```
Around 100 datasets are supplied with R. To see the list of datasets currently available use
```{chunk23, cache=TRUE}
data()
```
Using the function `str()` compactly display the internal structure of an R object:
```{chunk24, cache=TRUE}
str(object5)
```
Indexing a data frame is just like indexing a matrix:
```{chunk25, cache=TRUE}
object5[2,]
```
Due to the fact that the columns of a data frame have their own name you can also use the `$` operator to select elements of a data frame:
```{chunk26, cache=TRUE}
object5$colors2
object5$colors2[2]
```
Sometimes you may wish to select a partial quantity of a given data set then the `subset()` function is an appropriate choice. It returns subsets of data frames which meet conditions:
```{chunk27, cache=TRUE,results='hide'}
data(iris)
subset(iris, Species == "setosa")
subset(iris, Species == "setosa", select=c("Sepal.Length","Sepal.Width"))
```
\section{Packages}
All R functions and datasets are stored in packages. Only when a package is loaded are its
contents available. This is done both for efficiency (the full list would take more memory and
would take longer to search than a subset), and to aid package developers, who are protected
from name clashes with other code. To see which packages are installed at your site, issue the command
```{chunk28, cache=TRUE, results='hide'}
library()
```
with no arguments. To load a particular package use a command like
```{chunk29, cache=TRUE, results='hide' }
library(multcomp)
```
Users connected to the Internet can use the `install.packages()` and `update.packages()` functions to install and update packages. To see which packages are currently loaded, use 
```{chunk30, cache=TRUE ,results='hide'}
search()
```
The standard (or base) packages are considered part of the R source code. They contain the
basic functions that allow R to work, and the datasets and standard statistical and graphical
functions.
\section{Getting help with functions}
There are many functions in R which are designed to do all sorts of things. R has an inbuilt help facility to get more information on any specific named function, for example `seq()`:
A useful supplement to `help()` is the `example` function:
```{chunk31, cache=TRUE, results='hide'}
example(seq)
```
You can also use `help.search()` when you do not know the function name. Another function that is often used is the `help.search()`:
```{chunk32, cache=TRUE,results='hide'}
help.search("se")
```

